# Generated by Django 4.2.3 on 2023-10-19 14:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_projects"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Projects",
            new_name="Project",
        ),
    ]
